"""The checked-in demo workspace must stay identical to the fixture it came from.

`demo/repo` is generated by `tests/fixtures.py::write_fixture()` and then committed,
because `docker/docker-compose.yml` mounts it by default. While it was ignored, the
compose default mount silently became an *empty* directory (Docker creates missing
bind-mount sources) and `docker compose up` produced a normal-looking empty bundle --
zero findings, no error, nothing to notice.

Committing a generated directory introduces the opposite risk, so this file closes it:
if the fixture and the committed copy drift apart, the demo stops demonstrating the
thing the test-suite asserts, and every screenshot and doc number goes stale with it.
"""

from __future__ import annotations

from pathlib import Path

from tests.fixtures import FILES, write_fixture

REPO = Path(__file__).resolve().parents[1]
DEMO_REPO = REPO / "demo" / "repo"


def test_demo_repo_is_committed_and_not_ignored() -> None:
    """The directory has to exist in a fresh checkout, not just after `demo.py`."""
    assert DEMO_REPO.is_dir(), (
        "demo/repo is missing from the checkout. It is committed on purpose: "
        "docker-compose.yml mounts it by default, and a missing mount source turns "
        "into an empty directory that scans to a zero-finding bundle."
    )
    assert set(FILES) <= {p.name for p in DEMO_REPO.glob("*.py")}


def test_committed_demo_repo_matches_the_fixture(tmp_path: Path) -> None:
    """Generate the fixture elsewhere and compare byte for byte."""
    generated = write_fixture(tmp_path / "repo")
    for name in FILES:
        committed = (DEMO_REPO / name).read_text(encoding="utf-8")
        assert committed == (generated / name).read_text(encoding="utf-8"), (
            f"demo/repo/{name} has drifted from tests/fixtures.py. Regenerate it with "
            "`python scripts/demo.py`, or update the fixture if the change was intended."
        )


def test_write_fixture_is_idempotent(tmp_path: Path) -> None:
    """`demo.py` re-runs over the committed copy, so it must not rewrite equal files."""
    root = write_fixture(tmp_path / "repo")
    stamps = {p.name: p.stat().st_mtime_ns for p in root.glob("*.py")}
    write_fixture(root)
    assert {p.name: p.stat().st_mtime_ns for p in root.glob("*.py")} == stamps
